# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Manifestapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Manifestapp
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'ManifestappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

